### ISSUE TITLE
Missing hyperparameters not throwing error

### ISSUE THREAD

**Issue by johnpaulgosling** [andy-iskauskas/hmer#2]
The following code:
`matern(data.frame(x=1),data.frame(x=2),list(nu=1.5))`
is missing the `theta` parameter.
It returns `numeric(0)` rather than giving a useful error and it could lead to issues if the function was used in a loop. Is it possible to add a check that the parameters have been specified?

**Comment by andy-iskauskas** [comment]
This should be fixed now in v1.0.1 (currently on github; hopefully soon to be on CRAN). Running the line of code in your example the function now returns `No correlation length theta specified` and stops, which should avoid problematic behaviour!
